require('plugins-setup')

require('globals')
require('plugins.nvim-tree')
require('plugins.deferred-clipboard')
require('plugins.telescope')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.zenmode')
require('plugins.toggleterm')
require('plugins.undotree')
require('plugins.symbols-outline')
require('plugins.autoclose')
require('plugins.comment')
require('plugins.lualine')
require('plugins.onedark')

-- require('plugins.auto-save')
-- require('plugins.indent-blankline')
